#!/usr/bin/env sh

# 기본 레이아웃 설정
yabai -m config layout bsp

# 윈도우 간격 설정
yabai -m config top_padding    12
yabai -m config bottom_padding 12
yabai -m config left_padding   12
yabai -m config right_padding  12
yabai -m config window_gap     06

# 마우스 설정
yabai -m config mouse_follows_focus on
yabai -m config focus_follows_mouse autoraise
