#!/usr/bin/env sh

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

# 이진트리 레이아웃 설정
yabai -m config layout bsp

# 창 간격 설정
yabai -m config top_padding    10
yabai -m config bottom_padding 10
yabai -m config left_padding   10
yabai -m config right_padding  10
yabai -m config window_gap     10

yabai -m space 1 --display 1  
yabai -m space 2 --display 2  
yabai -m space 3 --display 3 
